[package]
name = "avrtest"
version = "0.1.0"
authors = ["Dylan McKay <me@dylanmckay.io>"]

[[bin]]
name = "avrlit"
path = "src/avrlit/main.rs"

[[bin]]
name = "avrsim"
path = "src/avrsim/main.rs"

[dependencies]
lit = "0.2.4"
simavr-sys = { path = "../simavr-sys", features = ["trace"] }
bitflags = "0.9"
tempfile = "2.1"

