[package]
name = "avr-sim"
version = "0.1.0"
authors = ["Dylan McKay <me@dylanmckay.io>"]
edition = "2018"

[dependencies]
bitflags = "1.0"
clap = "2.33"
gimli = "0.21.0"
object = "0.19"
simavr-sys = "1.5"
tempfile = "3.0"
vsprintf = "1.0"
